### ISSUE TITLE
Add more dart linter rules

### ISSUE THREAD

**Issue by qdot** [intiface/intiface-central#49]
```yaml
linter:
  rules:
    avoid_redundant_argument_values: true
    use_super_parameters: true
    directives_ordering: true
    sort_constructors_first: true
    unawaited_futures: true
```

https://dart-lang.github.io/linter/lints/index.html
